version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  nginx:
    image: nginx
    container_name: nginx-profbit
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/profbit
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - profbit_network
    depends_on:
      - database
  profbit:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: profbit
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/profbit
    networks:
      - profbit_network
  database:
    image: mariadb:latest
    container_name: mariadb-profbit
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - database_data:/var/lib/mariadb/data:rw
    networks:
      - profbit_network

networks:
  profbit_network:

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
